# Generated by Django 4.2.16 on 2026-03-04 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_servicefeedback_propertyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['approval_status'], name='myapp_prope_approva_fe0fec_idx'),
        ),
    ]
