# Generated by Django 4.2.16 on 2026-03-04 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0006_property_approval_note_property_approval_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["user", "created_at"], name="myapp_usera_user_id_a03d7d_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["path", "created_at"], name="myapp_usera_path_6d867f_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["status_code"], name="myapp_usera_status__63058e_idx"),
        ),
    ]
